import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,mkdirSync,writeFileSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {execFileSync} from 'node:child_process';
import {createServer} from 'node:http';
import {projectProviderKey,providerHeaders,PROVIDER_HEADER} from '../src/provider-key.mjs';
import {sanitizeCrash} from '../src/watch.mjs';
import {createMemoryStore} from '../src/store.mjs';
import {createGradula} from '../src/gradula.mjs';
import {createApi} from '../src/api.mjs';
import {PILOT} from '../src/decision-pilot.mjs';
const input={requestId:'byok',kind:'route',summary:'Find the function definition.',baseline:'lookup',candidates:[{id:'lookup',description:'Look up a source definition.'},{id:'reason',description:'Compare architecture alternatives.'}]};
const answer=()=>new Response(JSON.stringify({model:PILOT.model,answers:{selection:{choice:'lookup',confidence:1,probabilities:{lookup:1,reason:0,fallback:0}}},usage:{input_tokens:200}}));
test('provider env is project-scoped, worktree-aware, overridable, and never read for other calls',t=>{
 const home=mkdtempSync(join(tmpdir(),'gradula-provider-'));t.after(()=>rmSync(home,{recursive:true,force:true}));
 const root=join(home,'project'),tree=join(home,'worktree'),other=join(home,'other');mkdirSync(root);mkdirSync(other);
 const git=(...args)=>execFileSync('git',['-C',root,...args],{stdio:'pipe'});
 git('init','-q');git('-c','user.name=Fixture','-c','user.email=fixture@example.test','commit','--allow-empty','-qm','Fixture');
 writeFileSync(join(root,'.env'),'UNRELATED=value\nTYPESAFE_API_KEY=project-key\n',{mode:0o600});
 writeFileSync(join(home,'.env'),'TYPESAFE_API_KEY=parent-key\n');
 git('worktree','add','-qb','fixture-worktree',tree);
 assert.equal(projectProviderKey({cwd:tree,env:{}}),'project-key');
 assert.equal(projectProviderKey({cwd:other,env:{}}),null,'no parent or sibling key inheritance');
 writeFileSync(join(tree,'.env'),'TYPESAFE_API_KEY=worktree-key\n');
 assert.equal(projectProviderKey({cwd:tree,env:{}}),'worktree-key');
 assert.equal(projectProviderKey({cwd:tree,env:{TYPESAFE_API_KEY:'environment-key'}}),'environment-key');
 assert.equal(projectProviderKey({cwd:tree,env:{TYPESAFE_API_KEY:''}}),null);
 const poison={get TYPESAFE_API_KEY(){throw Error('Should never read this key');}};
 assert.deepEqual(providerHeaders('https://board.test','/api/v1/cards','GET',{cwd:tree,env:poison}),{});
 assert.deepEqual(providerHeaders('https://board.test','/api/v1/decision-trials','GET',{cwd:tree,env:poison}),{});
 assert.equal(providerHeaders('https://board.test','/api/v1/decision-trials','POST',{cwd:tree,env:{}})[PROVIDER_HEADER],'worktree-key');
 assert.throws(()=>providerHeaders('http://board.test','/api/v1/decision-trials','POST',{cwd:tree,env:{}}),/HTTPS/);
 assert.ok(providerHeaders('http://127.0.0.1:3200','/api/v1/decision-trials','POST',{cwd:tree,env:{}})[PROVIDER_HEADER]);
 assert.throws(()=>projectProviderKey({cwd:tree,env:{TYPESAFE_API_KEY:'key\nHeader: secret'}}),/format/);
});
test('project supplied keys override the instance key, are never retained, and never fall back on provider failure',async()=>{
 const store=createMemoryStore(),seen=[];
 const g=createGradula(store,{decisionPilot:{apiKey:'operator-key',projects:['PRB','OTH'],fetchImpl:async(_url,{headers})=>{seen.push(headers.Authorization);return answer();}}});
 await g.createProject({key:'PRB',name:'Probe'});await g.createProject({key:'OTH',name:'Other'});
 const first=await g.decisionTrial('PRB',input,'Alice','project-a-key');
 await g.decisionTrial('OTH',input,'Bob','project-b-key');
 assert.deepEqual(seen,['Bearer project-a-key','Bearer project-b-key']);
 assert.equal(JSON.stringify(first).includes('project-a-key'),false);
 assert.equal(JSON.stringify(await store.decisions.list('PRB',PILOT.campaign)).includes('project-a-key'),false);
 await g.decisionTrial('PRB',{...input,requestId:'operator'},'Alice');assert.equal(seen.at(-1),'Bearer operator-key');
 let calls=0;const failing=createGradula(store,{decisionPilot:{apiKey:'operator-key',projects:['PRB'],fetchImpl:async(_url,{headers})=>{calls++;assert.equal(headers.Authorization,'Bearer bad-project-key');return new Response('',{status:401});}}});
 const failed=await failing.decisionTrial('PRB',{...input,requestId:'failed'},'Alice','bad-project-key');assert.equal(failed.trial.result.status,'unavailable');assert.equal(calls,1);
});
test('allowlist still controls BYOK; missing keys consume no attempts and reports reveal no secrets',async()=>{
 const store=createMemoryStore(),g=createGradula(store,{decisionPilot:{projects:['PRB'],fetchImpl:async()=>answer()}});
 await g.createProject({key:'PRB',name:'Probe'});await g.createProject({key:'OTH',name:'Other'});
 assert.equal((await g.decisionTrial('OTH',input,'Bob','project-key')).status,'disabled');
 assert.equal((await g.decisionTrial('PRB',input,'Alice')).status,'key-required');
 const report=await g.decisionReport('PRB');assert.equal(report.enabled,true);assert.equal(report.providerKeyRequired,true);assert.equal(report.attempts,0);
 assert.equal((await g.decisionTrial('PRB',input,'Alice','project-key')).trial.result.status,'answered');
});
test('HTTP accepts the request-scoped key only after project authentication',async t=>{
 const keys=[],g=createGradula(createMemoryStore(),{decisionPilot:{projects:['PRB'],fetchImpl:async(_url,{headers})=>{keys.push(headers.Authorization);return answer();}}});
 await g.createProject({key:'PRB',name:'Probe'});const token=await g.mintToken('PRB','test','test','system');
 const server=createServer(createApi(g));await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));t.after(()=>new Promise(resolve=>server.close(resolve)));
 const url=`http://127.0.0.1:${server.address().port}/api/v1/decision-trials`;
 const request=async(auth)=>fetch(url,{method:'POST',headers:{...(auth?{Authorization:`Bearer ${token.token}`} : {}),'Content-Type':'application/json',[PROVIDER_HEADER]:'private-project-key'},body:JSON.stringify(input)});
 assert.equal((await request(false)).status,401);assert.equal(keys.length,0);
 const response=await request(true);assert.equal(response.status,200);const result=await response.json();assert.equal(result.trial.result.status,'answered');assert.deepEqual(keys,['Bearer private-project-key']);assert.equal(JSON.stringify(result).includes('private-project-key'),false);
});
test('crash events exclude provider and authentication headers, bodies and breadcrumb headers',()=>{
 const event={request:{headers:{Authorization:'board-key','X-Gradula-Typesafe-Key':'provider-key',Cookie:'session'},data:'private body',cookies:['cookie']},breadcrumbs:[{data:{headers:{'x-gradula-typesafe-key':'provider-key'},request_headers:{authorization:'board-key'},body:'private body',status_code:500}}]};
 const sanitized=JSON.stringify(sanitizeCrash(event));for(const secret of ['provider-key','board-key','private body','session','cookie'])assert.equal(sanitized.includes(secret),false);assert.ok(sanitized.includes('500'));
});
test('CLI sends project keys only to the configured board and refuses credential-bearing redirects',async t=>{
 const {promisify}=await import('node:util');const {execFile}=await import('node:child_process');const {fileURLToPath}=await import('node:url');
 const run=promisify(execFile),root=mkdtempSync(join(tmpdir(),'gradula-provider-cli-'));t.after(()=>rmSync(root,{recursive:true,force:true}));
 const file=join(root,'trial.json');writeFileSync(file,JSON.stringify(input));
 let leaked=0,received=null,redirect=false;
 const destination=createServer((_req,res)=>{leaked++;res.end('{}');});await new Promise(r=>destination.listen(0,'127.0.0.1',r));t.after(()=>new Promise(r=>destination.close(r)));
 const origin=createServer((req,res)=>{received=req.headers['x-gradula-typesafe-key'];if(redirect){res.writeHead(307,{location:`http://127.0.0.1:${destination.address().port}/capture`});res.end();}else{res.setHeader('content-type','application/json');res.end('{"status":"complete"}');}});
 await new Promise(r=>origin.listen(0,'127.0.0.1',r));t.after(()=>new Promise(r=>origin.close(r)));
 const options={cwd:root,env:{...process.env,GRADULA_URL:`http://127.0.0.1:${origin.address().port}`,GRADULA_TOKEN:'fixture-board',GRADULA_AGENT_TOKEN:'fixture-board',TYPESAFE_API_KEY:'fixture-provider'}};
 const args=[fileURLToPath(new URL('../bin/gradula.mjs',import.meta.url)),'decision-trial',file];
 await run(process.execPath,args,options);assert.equal(received,'fixture-provider');
 redirect=true;await assert.rejects(run(process.execPath,args,options));assert.equal(leaked,0);
});
