import test from 'node:test';
import assert from 'node:assert/strict';
import {createMemoryStore} from '../src/store.mjs';
import {createGradula} from '../src/gradula.mjs';
import {plannedPaths,workWarnings} from '../src/reservations.mjs';
const builds=[['memory',async()=>createMemoryStore()]];
if(process.env.GRADULA_DB_URL) builds.push(['Postgres',async()=>{const {createPgStore}=await import('../src/store-pg.mjs');const s=await createPgStore(process.env.GRADULA_DB_URL,{schema:`reserve_${Date.now()}`});await s.migrate();return s;}]);
for(const [name,build] of builds) test(`${name}: concurrent starts, ownership, takeover, stale sessions and release`,async t=>{
 const store=await build();t.after(()=>store.close?.());const g=createGradula(store);await g.createProject({key:'PRB',name:'Probe'});
 const c=await g.addItem('PRB',{kind:'task',title:'One task'},'person');
 const a={owner:'a',session:'a-session',files:['src/audio']};const b={owner:'b',session:'b-session',files:['src/audio/engine.rs']};
 const attempts=await Promise.allSettled([g.startItem(c.key,'Alice',a),g.startItem(c.key,'Bob',b)]);
 assert.equal(attempts.filter(x=>x.status==='fulfilled').length,1);
 const held=await g.getItem(c.key);const owner=held.reservation.owner==='a'?a:b;const other=owner===a?b:a;
 await assert.rejects(g.beat(c.key,'fake',other),e=>e.code==='reserved');
 await assert.rejects(g.startItem(c.key,'fake',other),e=>e.code==='reserved');
 await g.beat(c.key,'owner',owner);
 await g.startItem(c.key,'New owner',{...other,takeover:'Agreed handover'});
 await assert.rejects(g.beat(c.key,'old',owner),e=>e.code==='reserved');
 assert.ok((await g.getItem(c.key)).history.some(e=>e.data?.takeover==='Agreed handover'));
 const reserved=(await g.getItem(c.key)).reservation;
 await store.items.patch(c.key,{reservation:{...reserved,until:new Date(0).toISOString()},heartbeat:new Date(0).toISOString()});
 await assert.rejects(g.beat(c.key,'expired',other),e=>e.code==='expired');
 assert.deepEqual(await g.releaseStalled('PRB',{hours:0}),[],'unknown activity is not discarded');
 assert.equal((await g.getItem(c.key)).state,'making');
 await g.startItem(c.key,'Again',owner);
 await g.releaseWork(c.key,'Again',owner);
 assert.equal((await g.getItem(c.key)).reservation,null);
 assert.equal((await g.getItem(c.key)).state,'making');
 await g.startItem(c.key,'Again',owner);await g.moveItem(c.key,'review','reviewer');
 assert.equal((await g.getItem(c.key)).reservation,null);
});
test('planned paths and overlap warnings include directories, people and stale work',()=>{
 assert.deepEqual(plannedPaths(['./src/audio/','src/audio']),['src/audio']);
 for(const p of ['/Users/x/a','../a','a/../b','C:\\x','a\u0000b'])assert.throws(()=>plannedPaths([p]));
 const a={key:'A',module:['audio'],reservation:{files:['src/audio']}};
 const b={key:'B',state:'making',module:['audio'],reservation:{actor:'Bob',files:['src/audio/main.rs'],until:new Date(0).toISOString()}};
 const warnings=workWarnings(a,[b]);assert.equal(warnings[0].level,'files');assert.equal(warnings[0].actor,'Bob');assert.equal(warnings[0].activity,'unknown');
 assert.equal(workWarnings({...a,reservation:{files:['src/video']}},[b])[0].level,'module');
});
