import test from 'node:test';
import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {execFileSync,execFile} from 'node:child_process';
import {promisify} from 'node:util';
import {fileURLToPath} from 'node:url';
import {createApi} from '../src/api.mjs';
import {createGradula} from '../src/gradula.mjs';
import {createMemoryStore} from '../src/store.mjs';
test('sync attributes explicit Plan commits, and inherits a branch only within an explicit range',async t=>{
 const dir=mkdtempSync(join(tmpdir(),'gradula-sync-scope-'));t.after(()=>rmSync(dir,{recursive:true,force:true}));
 const cleanEnv=Object.fromEntries(Object.entries(process.env).filter(([key])=>!key.startsWith('GIT_')&&!key.startsWith('GRADULA_')));
 const git=(...args)=>execFileSync('git',args,{cwd:dir,encoding:'utf8',env:cleanEnv}).trim();
 git('init','-b','dev');git('config','user.name','Fixture');git('config','user.email','fixture@example.invalid');git('config','core.hooksPath','/dev/null');
 git('commit','--allow-empty','-m','Unrelated old work');const old=git('rev-parse','HEAD');
 git('switch','-c','codex/PRB-1');git('commit','--allow-empty','-m','New task work');const fresh=git('rev-parse','HEAD');
 git('commit','--allow-empty','-m','Merge unrelated history');const merge=git('rev-parse','HEAD');
 git('commit','--allow-empty','-m','Explicit task proof','-m','Plan: PRB-1');const named=git('rev-parse','HEAD');
 const store=createMemoryStore(),g=createGradula(store),server=createServer(createApi(g,{adminToken:'test-admin'}));
 await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));t.after(()=>new Promise(resolve=>server.close(resolve)));
 const base=`http://127.0.0.1:${server.address().port}`;
 const post=async(path,body)=>{const r=await fetch(base+path,{method:'POST',headers:{authorization:'Bearer test-admin','content-type':'application/json'},body:JSON.stringify(body)});assert.ok(r.ok);return r.json()};
 await post('/api/admin/projects',{key:'PRB',name:'Fixture'});const {token}=await post('/api/admin/projects/PRB/keys',{name:'Fixture'});
 const card=await g.addItem('PRB',{kind:'task',title:'New work'},'Fixture');
 const cli=fileURLToPath(new URL('../bin/gradula.mjs',import.meta.url));
 const run=args=>promisify(execFile)(process.execPath,[cli,'sync',...args],{cwd:dir,env:{...cleanEnv,GRADULA_URL:base,GRADULA_TOKEN:token,GRADULA_AGENT_TOKEN:token,GRADULA_HAND:'agent'}});
 const refs=async()=>(await store.events.of(card.id)).filter(e=>e.verb==='evidenced').map(e=>e.data.ref);
 await run([]);assert.deepEqual(await refs(),[named.slice(0,12)]);
 await run(['--since',old]);assert.deepEqual(new Set(await refs()),new Set([named.slice(0,12),fresh.slice(0,12)]));
 assert.ok(!(await refs()).includes(old.slice(0,12)));assert.ok(!(await refs()).includes(merge.slice(0,12)));
});
