/**
 * The board speaks two languages; the data speaks one.
 *
 * THAT IS THE WHOLE RULE. A state is `making` in the database, in the URL and
 * in SQL, and it is "Arbeit" or "Making" only where a person reads it. A value
 * that changed with the language setting would silently break every link ever
 * built — which is why nothing here ever reaches an API.
 *
 * The vocabulary (kinds, states, targets, link kinds) is deliberately NOT
 * repeated here: it lives in `src/spec.mjs` as WORDS, and the service and the
 * board share it. A second list of the same words drifts apart, and then a
 * column is called something the herald does not know.
 *
 * Everything else — the sentences of this surface — stands below. English is
 * the source: the keys read like their English text, so a missing translation
 * is visible rather than silent.
 */
import { WORDS, LANGUAGES } from './vocabulary';
import type { Language } from './vocabulary';

export type { Language };
export { LANGUAGES };

/** The sentences of the surface. English is written out; German is the twin. */
const SURFACE: Record<Language, Record<string, string>> = {
  en: {
    'ui.app': 'Gradula',
    'ui.loading': 'Loading…',
    'ui.retry': 'Try again',
    'ui.project': 'Project',
    'ui.views': 'Workspace views',
    'ui.newCard': 'New card',
    'ui.filters': 'Filters',
    'ui.clearFilters': 'Clear filters',
    'ui.area': 'Area',
    'ui.module': 'Module',
    'ui.craft': 'Craft',
    'ui.stages': 'Workflow stages',
    'ui.kind': 'Kind',
    'ui.confirm': 'Confirm',
    'ui.unsaved': 'You have unsaved changes. Keep editing or discard them?',
    'ui.keepEditing': 'Keep editing',
    'ui.retrySave': 'Could not check the latest card. Your changes are kept; try saving again.',
    'ui.editConflict': 'Someone changed a field you are editing. Your draft is kept. Review the latest card before saving.',
    'ui.noProjects': 'No project connected',
    'ui.noProjectsWhy': 'Connect a project to start collecting ideas, work and evidence.',
    'ui.noResults': 'No cards match these filters',
    'ui.noResultsWhy': 'Try a broader search or clear the filters.',
    'ui.emptyBoard': 'A clear board. What comes next?',
    'ui.emptyBoardWhy': 'Capture an idea or add a task that is ready to work on.',
    'ui.newCardHint': 'Ideas wait for approval. Tasks start in Ready. You can add proof and an owner later.',
    'empty.ideas': 'Possibilities waiting for a decision.',
    'empty.ready': 'Approved and ready to begin.',
    'empty.making': 'Work in progress appears here.',
    'empty.review': 'Finished work awaiting a check.',
    'empty.done': 'Completed work, with its evidence.',
    'empty.ice': 'Paused work, kept for later.',
    'settings.channels': 'Channels',
    'settings.reports': 'Reports',
    'settings.access': 'Access',
    'settings.public': 'Public',
    'settings.internal': 'Internal',
    'settings.active': 'Active',
    'settings.paused': 'Paused',
    'settings.pause': 'Pause',
    'settings.resume': 'Resume',
    'settings.custom': 'Custom event filter',
    'settings.reportAudience': 'Reports include internal work and can be sent to active internal channels. Public channels receive only published updates.',
    'sign.claim': 'Where a wish climbs to true.',
    'sign.in': 'Sign in',
    'sign.walking': 'Taking you there…',
    'sign.note': 'With your Mundula account. Without the role dev this door stays shut.',
    'nav.board': 'Board',
    'nav.pulse': 'Pulse',
    'nav.legend': 'Legend',
    'nav.menu': 'More',
    'card.byHand': 'move by hand',
    'level.fatal': 'fatal',
    'level.error': 'error',
    'level.warning': 'warning',
    'level.info': 'info',
    'level.debug': 'debug',
    'legend.levels': 'How bad it was',
    'legend.levelsWhy': "Sentry's own word for how loud a crash was. Not a state — moving the card does not change what the crash weighed — and not the beam: the beam says you are needed, this says how hard it hit.",
    'card.approve': 'approve',
    'card.approvedReason': 'reviewed and approved',
    'card.sendBack': 'send back',
    'card.sendBackWhy': 'What is still missing? The sentence becomes the reason.',
    'card.sendBackReason': 'sent back from review',
    'card.gateProves': 'the gate decides — done only while it is green',
    'card.onItsWay': 'on its way — seen on dev; production moves it to done by itself. Look at dev, or send it back.',
    'map.how': 'The centre is the first card, the rim is now.',
    'map.areas': 'areas',
    'map.cards': 'cards',
    'map.clickArea': 'Click an area or a state to narrow it down.',
    'map.filtered': 'Press the same one again for everything.',
    'map.born': 'written',
    'map.untouched': 'untouched',
    'nav.allCrafts': 'all crafts',
    'card.overdue': 'overdue',
    'card.overdueWhy': 'the date has passed and this is still open',
    'card.idleWhy': 'open, and nobody has touched it for this long',
    'legend.head': 'What the board is saying',
    'legend.signals': 'Motion',
    'legend.oneWarm': 'Motion always shows a fact from the board. Exactly one signal is warm, and it is the one that means you are needed.',
    'legend.working': 'in making',
    'legend.workingWhy': 'somebody put this card in making and left it there',
    'legend.attention': 'needs a hand',
    'legend.attentionWhy': 'a review somebody asked for, or labels nobody confirmed, or an open crash Sentry called fatal — a card the pipeline put in review (seen on dev, on its way to production) is quiet: look at dev, send it back if it is wrong, or let it go',
    'legend.changed': 'just changed',
    'legend.changedWhy': 'this moved while you were looking — it ends by itself',
    'legend.marks': 'Marks',
    'legend.orb': 'a runner',
    'legend.orbWhy': 'a machine is working on this AT THIS MOMENT — a lease that goes stale by itself when the laptop closes',
    'legend.labelsWhy': 'where in the repository · which craft · what a rule proposed and nobody confirmed',
    'legend.waitsWhy': 'a card it needs is not done — computed, never a tick somebody has to remember; start refuses it unless you say why',
    'card.toReady': 'to ready — that is the yes',
    'card.startAnyway': 'start anyway',
    'card.anywayWhy': 'It waits on …. Why start anyway? The sentence becomes the reason.',
    'legend.gateWhy': 'this card has something that proves it is done — without one it never moves there by itself, and with one no hand files it done while it is red',
    'legend.groups': 'Groups',
    'legend.ventureWhy': 'part of the same venture or milestone',
    'legend.kinds': 'Kinds',
    'legend.kindsWhy': 'A kind is not a state and gets no colour. It is shown only where it says something — `task` on twenty-nine of thirty-five cards would be noise.',
    'pulse.happened': 'What happened',
    'pulse.touched': 'cards touched',
    'pulse.nothing': 'Nothing moved in this period.',
    'pulse.done': 'done',
    'pulse.released': 'released',
    'pulse.decided': 'decided',
    'pulse.incidents': 'incidents',
    'pulse.started': 'started',
    'pulse.pace': 'Pace',
    'pulse.settledIn': 'settled in',
    'pulse.days': 'days',
    'pulse.perDay': 'per day',
    'pulse.sample': 'moves measured — a small sample says something about next week and nothing about next quarter',
    'pulse.goals': 'Where we are going',
    'pulse.noGoals': 'No milestone and no venture yet.',
    'pulse.ahead': 'in time',
    'pulse.tight': 'tight',
    'pulse.behind': 'behind',
    'pulse.noDate': 'no date',
    'pulse.noPace': 'no pace yet',
    'pulse.noParts': 'no parts',
    'pulse.settled': 'settled',
    'pulse.daysOfWork': 'd of work',
    'pulse.daysLeft': 'd left',
    'pulse.energy': 'Where the energy went',
    'pulse.module': 'Module',
    'pulse.craft': 'Craft',
    'pulse.people': 'People',
    'pulse.noLabels': 'nothing labelled',
    'pulse.nowhere': 'no label',
    'pulse.nowhereWhy': 'These moves carry no label on this axis. Until they do, this picture is about a part of the work, not about the work.',
    'pulse.hangs': 'What it hangs on',
    'pulse.nothingHangs': 'Nothing is waiting on anything.',
    'pulse.board': 'The board itself',
    'pulse.boardClean': 'Nothing to tidy.',
    // The findings come from the service with an id and an English line. The
    // id is the address; the sentence belongs to whoever reads it. A finding
    // the surface does not know still shows the line the service sent.
    'finding.no-gate': 'open tasks without a gate',
    'finding.no-gate.why': 'a task without a gate never reaches done on its own',
    'finding.stalled': 'cards in making with no runner',
    'finding.stalled.why': 'either somebody works without saying so, or nobody works',
    'finding.overdue': 'milestones past their date',
    'finding.overdue.why': 'the date passed and the milestone is still open',
    'finding.incidents': 'open incidents from Sentry',
    'finding.incidents.why': 'a crash nobody touched is a crash that comes back',
    'finding.unconfirmed': 'labels waiting for a hand',
    'finding.unconfirmed.why': 'a suggestion changes nothing until a hand confirms it',
    'finding.quiet': 'open cards nobody has touched lately',
    'finding.quiet.why': 'not an accusation, a question: is this still wanted?',
    'finding.unlabelled': 'open cards with no label at all',
    'finding.unlabelled.why': 'no module and no craft — invisible to every filter and to the map',
    'finding.other-language': "cards not written in this board's language",
    'finding.other-language.why': 'a board half in one language and half in another cannot be searched',
    'finding.no-parts': 'milestones and ventures with no parts',
    'finding.no-parts.why': 'a milestone without parts is unanswered, not at zero',
    'nav.map': 'Map',
    'nav.settings': 'Settings',
    'herald.pipeline': 'Live pipeline progress (internal)',
    'herald.pipelineWhy': 'One message per GitHub workflow attempt, updated about every minute. Circles show card progress; squares show actual job steps. Outside receives published updates only.',
    'nav.heralds': 'Heralds',
    'nav.search': 'Find a card',
    'card.new': 'New card',
    'card.create': 'Create card',
    'bond.venture': 'part of',
    'card.close': 'Close',
    'card.use': 'use',
    'card.say2': 'Add comment',
    'card.editing': 'editing',
    'card.running': 'a runner is working on this right now',
    'card.sentry': 'view in Sentry',
    'card.discard': 'Discard',
    'nav.allModules': 'all modules',
    'nav.allAreas': 'all areas',
    'herald.voiceHuman': 'human — titles and reasons',
    'herald.voicePlain': 'plain — keys, labels, gates',
    'herald.chatId': "-100… or a person's id",
    'report.period': 'this week',
    'map.empty': 'Nothing to draw yet.',
    'card.title': 'What is to be done?',
    'card.text': 'Situation, intent, acceptance — and when another card is meant, name it (MDLA-1).',
    'card.save': 'Save',
    'card.cancel': 'Cancel',
    'card.edit': 'Edit',
    'card.start': 'Start work',
    'card.say': 'say something',
    'card.decide': 'decide — the text becomes the reason',
    'card.decided': 'What has been decided? (briefly)',
    'card.person': 'Person',
    'card.nobody': 'nobody yet',
    'card.newPerson': 'somebody new…',
    'card.personName': 'their name, as the chronicle will use it',
    'card.pickFile': 'pick a file',
    'card.otherFile': 'another path…',
    'card.pathExample': 'packages/…/x.ts',
    'card.gate': 'Gate',
    'card.gateNone': 'no gate',
    'card.gateExpect': 'expected (200, say) — may stay empty',
    'card.gateMissing': 'no gate — production decides: seen on main, it is done',
    'card.suggested': 'Suggested labels, not confirmed',
    'card.confirm': 'take over',
    'card.waits': 'waits for',
    'keys.head': 'Your keys — for the CLI and the MCP server on your machine',
    'keys.login': 'Fastest: run gradula login on the machine — it names itself and writes its own .gradula.env, with a key for you and one for your AI sessions. Approve it here.',
    'keys.pending': 'A machine is asking to register',
    'keys.approve': 'approve',
    'keys.deny': 'deny',
    'keys.code': 'code',
    'keys.none': 'No key yet. Name your machine and mint one — it is shown once.',
    'keys.machine': 'name of the machine',
    'keys.mint': 'mint',
    'keys.once': 'Shown once. Put these lines into .gradula.env in the repository — the key speaks as you; no actor line needed.',
    'keys.revoke': 'revoke',
    'keys.agent': 'the key your AI sessions take — the chronicle names the active coder and registered machine',
    'keys.used': 'last used',
    'keys.never': 'never',
    'keys.copy': 'copy',
    'keys.copied': 'copied',
    'herald.head': 'Heralds — what leaves the house',
    'herald.none': 'No herald yet. A herald speaks outward and never carries a key with it.',
    'herald.noChats': 'none yet — invite the bot into the group, or send it /start',
    'door.ladder': 'the columns a card climbs',
    'herald.new': 'New herald',
    'herald.edit': 'Edit herald',
    'herald.name': 'Name',
    'herald.namePlaceholder': 'Workshop',
    'herald.nameWhy': 'What this herald is called on the board. Only for you — nothing outside ever sees it.',
    'herald.key': 'Bot key',
    'herald.houseKey': 'use the house key — the bot the server already knows',
    'herald.houseKeyWhy': 'The key stays on the server (TELEGRAM_BOT_TOKEN); this herald only says "the house key". The channels the house bot can see are listed below — invite it into a group first, or send it /start.',
    'herald.keyPlaceholder': '1234567890:AA…',
    'herald.keyKept': 'set — leave empty to keep it',
    'herald.keyWhy': 'The bot\'s key from Telegram: @BotFather → /mybots → your bot → API Token. It stays in this board and never goes into a message.',
    'herald.pickChat': 'pick a channel',
    'herald.chatWhy': 'Invite the bot into the group first, or send it /start. Then press the button — Telegram then knows the channel and the board can list it.',
    'herald.template': 'Template',
    'herald.cadence': 'The report, by itself — moves and releases go out at once regardless',
    'herald.cadenceOff': 'only when I press send',
    'herald.daily': 'daily',
    'herald.weekly': 'weekly',
    'herald.atHour': 'at',
    'herald.keepFilter': 'keep the filter',
    'herald.templateWhy': 'A template is a filled-in filter, nothing more. Take one, change a line, and it is yours.',
    'herald.probe': 'Probe',
    'herald.remove': 'Remove',
    'herald.chats': 'Find channels',
    'herald.quiet': 'Nothing is sent until you press send.',
    'report.head': 'Report — many moves, one message',
    'report.sent': 'Report delivered.',
    'report.saved': 'Saved.',
    'build.head': 'Build',
    'chat.head': 'Chat',
    // Where a card has arrived — the two chips and the line in the sheet.
    'lane.dev': 'dev',
    'lane.prod': 'prod',
    'card.onDev': 'on development — what dev runs holds this card\'s commits',
    'card.onProd': 'on production — what main runs holds this card\'s commits',
    'card.notOnDev': 'not on development yet',
    'card.notOnProd': 'not on production yet',
    'card.deployed': 'deployed',
  },
  de: {
    'ui.app': 'Gradula',
    'ui.loading': 'Wird geladen…',
    'ui.retry': 'Erneut versuchen',
    'ui.project': 'Projekt',
    'ui.views': 'Ansichten',
    'ui.newCard': 'Neue Karte',
    'ui.filters': 'Filter',
    'ui.clearFilters': 'Filter löschen',
    'ui.area': 'Bereich',
    'ui.module': 'Modul',
    'ui.craft': 'Gewerk',
    'ui.stages': 'Arbeitsschritte',
    'ui.kind': 'Art',
    'ui.confirm': 'Bestätigen',
    'ui.unsaved': 'Es gibt ungespeicherte Änderungen. Weiter bearbeiten oder verwerfen?',
    'ui.keepEditing': 'Weiter bearbeiten',
    'ui.retrySave': 'Die aktuelle Karte konnte nicht geprüft werden. Dein Entwurf bleibt erhalten; versuche es erneut.',
    'ui.editConflict': 'Ein bearbeitetes Feld wurde inzwischen geändert. Dein Entwurf bleibt erhalten. Prüfe die aktuelle Karte vor dem Speichern.',
    'ui.noProjects': 'Kein Projekt verbunden',
    'ui.noProjectsWhy': 'Verbinde ein Projekt, um Ideen, Arbeit und Belege zu sammeln.',
    'ui.noResults': 'Keine Karte passt zu diesen Filtern',
    'ui.noResultsWhy': 'Suche allgemeiner oder lösche die Filter.',
    'ui.emptyBoard': 'Ein freies Board. Was kommt als Nächstes?',
    'ui.emptyBoardWhy': 'Halte eine Idee fest oder füge eine Aufgabe hinzu, die bereit ist.',
    'ui.newCardHint': 'Ideen warten auf Freigabe. Aufgaben starten in Bereit. Belege und Zuständigkeit kannst du später ergänzen.',
    'empty.ideas': 'Möglichkeiten, die auf eine Entscheidung warten.',
    'empty.ready': 'Freigegeben und bereit zum Start.',
    'empty.making': 'Laufende Arbeit erscheint hier.',
    'empty.review': 'Fertige Arbeit wartet auf Prüfung.',
    'empty.done': 'Abgeschlossene Arbeit mit ihren Belegen.',
    'empty.ice': 'Pausierte Arbeit bleibt hier erhalten.',
    'settings.channels': 'Kanäle',
    'settings.reports': 'Berichte',
    'settings.access': 'Zugang',
    'settings.public': 'Öffentlich',
    'settings.internal': 'Intern',
    'settings.active': 'Aktiv',
    'settings.paused': 'Pausiert',
    'settings.pause': 'Pausieren',
    'settings.resume': 'Fortsetzen',
    'settings.custom': 'Eigener Ereignisfilter',
    'settings.reportAudience': 'Berichte enthalten interne Arbeit und gehen nur an aktive interne Kanäle. Öffentliche Kanäle erhalten ausschließlich veröffentlichte Updates.',
    'sign.claim': 'Wo ein Wunsch wahr wird.',
    'sign.in': 'Anmelden',
    'sign.walking': 'Einen Moment…',
    'sign.note': 'Mit deinem Mundula-Konto. Ohne die Rolle dev bleibt diese Tür zu.',
    'nav.board': 'Tafel',
    'nav.pulse': 'Puls',
    'nav.legend': 'Legende',
    'nav.menu': 'Mehr',
    'card.byHand': 'von Hand verschieben',
    'level.fatal': 'fatal',
    'level.error': 'Fehler',
    'level.warning': 'Warnung',
    'level.info': 'Info',
    'level.debug': 'Debug',
    'legend.levels': 'Wie schlimm es war',
    'legend.levelsWhy': 'Sentrys eigenes Wort dafür, wie laut ein Absturz war. Kein Zustand — die Karte zu verschieben ändert nicht, was der Absturz gewogen hat — und nicht der Beam: der Beam sagt, dass du gebraucht wirst, das hier sagt, wie hart es getroffen hat.',
    'card.approve': 'annehmen',
    'card.approvedReason': 'geprüft und angenommen',
    'card.sendBack': 'zurückgeben',
    'card.sendBackWhy': 'Was fehlt noch? Der Satz wird der Grund.',
    'card.sendBackReason': 'aus der Prüfung zurückgegeben',
    'card.gateProves': 'das Tor entscheidet — fertig nur, wenn es grün ist',
    'card.onItsWay': 'unterwegs — auf dev gesehen; die Produktion setzt sie von selbst auf fertig. Auf dev anschauen oder zurückgeben.',
    'map.how': 'Die Mitte ist die erste Karte, der Rand ist jetzt.',
    'map.areas': 'Bereiche',
    'map.cards': 'Karten',
    'map.clickArea': 'Klick auf einen Bereich oder einen Zustand, um einzugrenzen.',
    'map.filtered': 'Nochmal draufdrücken zeigt wieder alles.',
    'map.born': 'geschrieben',
    'map.untouched': 'unberührt',
    'nav.allCrafts': 'alle Gewerke',
    'card.overdue': 'überfällig',
    'card.overdueWhy': 'das Datum ist vorbei und das hier steht noch offen',
    'card.idleWhy': 'offen, und so lange hat niemand sie angefasst',
    'legend.head': 'Was die Tafel sagt',
    'legend.signals': 'Bewegung',
    'legend.oneWarm': 'Bewegung zeigt immer eine Tatsache vom Brett. Genau ein Signal ist warm, und es heißt: du wirst gebraucht.',
    'legend.working': 'in Arbeit',
    'legend.workingWhy': 'jemand hat die Karte auf Arbeit gesetzt und dort gelassen',
    'legend.attention': 'braucht eine Hand',
    'legend.attentionWhy': 'eine Prüfung, die jemand verlangt hat, oder Etiketten, die niemand bestätigt hat, oder ein offener Absturz, den Sentry fatal nennt — eine Karte, die die Pipeline in die Prüfung gestellt hat (auf dev gesehen, unterwegs zur Produktion), ist still: auf dev anschauen, zurückschicken, wenn sie falsch ist, oder gehen lassen',
    'legend.changed': 'gerade geändert',
    'legend.changedWhy': 'das hier hat sich bewegt, während du hingesehen hast — es endet von selbst',
    'legend.marks': 'Zeichen',
    'legend.orb': 'ein Läufer',
    'legend.orbWhy': 'eine Maschine arbeitet GERADE JETZT daran — eine Pacht, die von selbst abläuft, wenn der Rechner zugeht',
    'legend.labelsWhy': 'wo im Repository · welches Gewerk · was eine Regel vorgeschlagen und niemand bestätigt hat',
    'legend.waitsWhy': 'eine Karte, die sie braucht, ist nicht fertig — gerechnet, nie ein Haken, den jemand nachhalten muss; anfangen geht nur mit einem Grund',
    'card.toReady': 'nach Bereit — das ist das Ja',
    'card.startAnyway': 'trotzdem anfangen',
    'card.anywayWhy': 'Sie wartet auf …. Warum trotzdem anfangen? Der Satz wird der Grund.',
    'legend.gateWhy': 'diese Karte hat etwas, das beweist, dass sie fertig ist — ohne Tor kommt sie nie von selbst dorthin, und mit Tor legt keine Hand sie auf fertig, solange es rot ist',
    'legend.groups': 'Gruppen',
    'legend.ventureWhy': 'Teil desselben Vorhabens oder Meilensteins',
    'legend.kinds': 'Arten',
    'legend.kindsWhy': 'Eine Art ist kein Zustand und bekommt keine Farbe. Sie steht nur da, wo sie etwas sagt — `Aufgabe` auf 29 von 35 Karten wäre Rauschen.',
    'pulse.happened': 'Was passiert ist',
    'pulse.touched': 'Karten berührt',
    'pulse.nothing': 'In diesem Zeitraum hat sich nichts bewegt.',
    'pulse.done': 'fertig',
    'pulse.released': 'veröffentlicht',
    'pulse.decided': 'entschieden',
    'pulse.incidents': 'Vorfälle',
    'pulse.started': 'angefangen',
    'pulse.pace': 'Tempo',
    'pulse.settledIn': 'erledigt in',
    'pulse.days': 'Tagen',
    'pulse.perDay': 'pro Tag',
    'pulse.sample': 'Züge gemessen — eine kleine Stichprobe sagt etwas über nächste Woche und nichts über nächstes Quartal',
    'pulse.goals': 'Wo wir hinwollen',
    'pulse.noGoals': 'Noch kein Meilenstein und kein Vorhaben.',
    'pulse.ahead': 'im Plan',
    'pulse.tight': 'knapp',
    'pulse.behind': 'hinterher',
    'pulse.noDate': 'kein Datum',
    'pulse.noPace': 'noch kein Tempo',
    'pulse.noParts': 'keine Teile',
    'pulse.settled': 'erledigt',
    'pulse.daysOfWork': ' T Arbeit',
    'pulse.daysLeft': ' T übrig',
    'pulse.energy': 'Wohin die Energie ging',
    'pulse.module': 'Modul',
    'pulse.craft': 'Gewerk',
    'pulse.people': 'Leute',
    'pulse.noLabels': 'nichts etikettiert',
    'pulse.nowhere': 'ohne Etikett',
    'pulse.nowhereWhy': 'Diese Züge tragen auf dieser Achse kein Etikett. Solange das so ist, zeigt dieses Bild einen Teil der Arbeit, nicht die Arbeit.',
    'pulse.hangs': 'Woran es hängt',
    'pulse.nothingHangs': 'Nichts wartet auf etwas.',
    'pulse.board': 'Das Brett selbst',
    'pulse.boardClean': 'Nichts aufzuräumen.',
    'finding.no-gate': 'offene Aufgaben ohne Tor',
    'finding.no-gate.why': 'eine Aufgabe ohne Tor kommt nie von selbst auf fertig',
    'finding.stalled': 'Karten in Arbeit, an denen kein Läufer sitzt',
    'finding.stalled.why': 'entweder arbeitet jemand, ohne es zu sagen, oder niemand arbeitet',
    'finding.overdue': 'Meilensteine über ihrem Datum',
    'finding.overdue.why': 'das Datum ist vorbei und der Meilenstein steht noch offen',
    'finding.incidents': 'offene Vorfälle aus Sentry',
    'finding.incidents.why': 'ein Absturz, den niemand angefasst hat, kommt wieder',
    'finding.unconfirmed': 'Etiketten, die auf eine Hand warten',
    'finding.unconfirmed.why': 'ein Vorschlag ändert nichts, bevor eine Hand ihn übernimmt',
    'finding.quiet': 'offene Karten, die länger niemand angefasst hat',
    'finding.quiet.why': 'kein Vorwurf, eine Frage: ist das noch gewollt?',
    'finding.unlabelled': 'offene Karten ganz ohne Etikett',
    'finding.unlabelled.why': 'kein Modul und kein Gewerk — für jeden Filter und für die Karte unsichtbar',
    'finding.other-language': 'Karten, die nicht in der Sprache dieses Bretts stehen',
    'finding.other-language.why': 'ein Brett halb in einer und halb in der anderen Sprache lässt sich nicht durchsuchen',
    'finding.no-parts': 'Meilensteine und Vorhaben ohne Teile',
    'finding.no-parts.why': 'ein Meilenstein ohne Teile ist unbeantwortet, nicht bei null',
    'nav.map': 'Karte',
    'nav.settings': 'Einstellungen',
    'herald.pipeline': 'Live-Fortschritt der Pipeline (intern)',
    'herald.pipelineWhy': 'Eine Nachricht pro GitHub-Workflow-Versuch, etwa jede Minute aktualisiert. Kreise zeigen Kartenfortschritt; Quadrate zeigen die tatsächlichen Job-Schritte. Außen erscheinen nur veröffentlichte Updates.',
    'keys.head': 'Deine Schlüssel — für CLI und MCP-Server auf deinem Rechner',
    'keys.login': 'Am schnellsten: gradula login auf dem Rechner — er nennt sich selbst und schreibt seine .gradula.env, mit einem Schlüssel für dich und einem für deine KI-Sitzungen. Hier bestätigen.',
    'keys.pending': 'Ein Rechner möchte sich anmelden',
    'keys.approve': 'bestätigen',
    'keys.deny': 'ablehnen',
    'keys.code': 'Code',
    'keys.none': 'Noch kein Schlüssel. Nenn deinen Rechner und präge einen — er wird einmal gezeigt.',
    'keys.machine': 'Name des Rechners',
    'keys.mint': 'prägen',
    'keys.once': 'Wird einmal gezeigt. Diese Zeilen nach .gradula.env im Repository — der Schlüssel spricht als du, keine Akteur-Zeile nötig.',
    'keys.revoke': 'widerrufen',
    'keys.agent': 'der Schlüssel deiner KI-Sitzungen — die Chronik nennt sie „Claude Code · Rechner"',
    'keys.used': 'zuletzt benutzt',
    'keys.never': 'nie',
    'keys.copy': 'kopieren',
    'keys.copied': 'kopiert',
    'nav.heralds': 'Boten',
    'nav.search': 'Karte finden',
    'card.new': 'Neue Karte',
    'card.create': 'Karte anlegen',
    'bond.venture': 'Teil von',
    'card.close': 'schließen',
    'card.use': 'nehmen',
    'card.say2': 'Kommentieren',
    'card.editing': 'wird geändert',
    'card.running': 'hier arbeitet gerade ein Läufer',
    'card.sentry': 'in Sentry ansehen',
    'card.discard': 'verwerfen',
    'nav.allModules': 'alle Module',
    'nav.allAreas': 'alle Bereiche',
    'herald.voiceHuman': 'menschlich — Titel und Gründe',
    'herald.voicePlain': 'technisch — Schlüssel, Etiketten, Tore',
    'herald.chatId': '-100… oder die Kennung einer Person',
    'report.period': 'diese Woche',
    'map.empty': 'Noch nichts zu zeichnen.',
    'card.title': 'Was ist zu tun?',
    'card.text': 'Lage, Absicht, Abnahme — und wenn eine andere Karte gemeint ist, nenn sie beim Namen (MDLA-1).',
    'card.save': 'Sichern',
    'card.cancel': 'Abbrechen',
    'card.edit': 'Ändern',
    'card.start': 'Arbeit starten',
    'card.say': 'etwas sagen',
    'card.decide': 'entscheiden — der Text wird der Grund',
    'card.decided': 'Was ist entschieden? (kurz)',
    'card.person': 'Person',
    'card.nobody': 'noch niemand',
    'card.newPerson': 'jemand Neues…',
    'card.personName': 'der Name, wie die Chronik ihn führt',
    'card.pickFile': 'Datei wählen',
    'card.otherFile': 'anderer Pfad…',
    'card.pathExample': 'packages/…/x.ts',
    'card.gate': 'Tor',
    'card.gateNone': 'kein Tor',
    'card.gateExpect': 'Erwartung (etwa 200) — darf leer bleiben',
    'card.gateMissing': 'kein Tor — die Produktion entscheidet: auf main gesehen, ist sie fertig',
    'card.confirm': 'übernehmen',
    'card.suggested': 'Vorgeschlagene Etiketten, nicht bestätigt',

    'card.waits': 'wartet auf',
    'herald.head': 'Boten — was das Haus verlässt',
    'herald.none': 'Noch kein Bote. Ein Bote spricht hinaus und trägt nie einen Schlüssel mit.',
    'herald.noChats': 'noch keine — lade den Bot in die Gruppe, oder schick ihm /start',
    'door.ladder': 'die Spalten, die eine Karte hinaufsteigt',
    'herald.new': 'Neuer Bote',
    'herald.edit': 'Boten ändern',
    'herald.name': 'Name',
    'herald.namePlaceholder': 'Werkstatt',
    'herald.nameWhy': 'Wie dieser Bote auf dem Brett heißt. Nur für dich — nach außen sieht ihn niemand.',
    'herald.key': 'Bot-Schlüssel',
    'herald.houseKey': 'den Hausschlüssel nehmen — der Bot, den der Server schon kennt',
    'herald.houseKeyWhy': 'Der Schlüssel bleibt auf dem Server (TELEGRAM_BOT_TOKEN); dieser Herold sagt nur „der Hausschlüssel". Darunter stehen die Kanäle, die der Haus-Bot sieht — lade ihn zuerst in eine Gruppe ein oder schick ihm /start.',
    'herald.keyPlaceholder': '1234567890:AA…',
    'herald.keyKept': 'gesetzt — leer lassen, um ihn zu behalten',
    'herald.keyWhy': 'Der Schlüssel des Bots aus Telegram: @BotFather → /mybots → dein Bot → API Token. Er bleibt in diesem Brett und geht nie in eine Nachricht.',
    'herald.pickChat': 'Kanal wählen',
    'herald.chatWhy': 'Lade den Bot zuerst in die Gruppe ein, oder schick ihm /start. Dann auf den Knopf — danach kennt Telegram den Kanal und das Brett kann ihn auflisten.',
    'herald.template': 'Vorlage',
    'herald.cadence': 'Der Bericht, von selbst — Züge und Releases gehen ohnehin sofort raus',
    'herald.cadenceOff': 'nur wenn ich sende',
    'herald.daily': 'täglich',
    'herald.weekly': 'wöchentlich',
    'herald.atHour': 'um',
    'herald.keepFilter': 'Filter behalten',
    'herald.templateWhy': 'Eine Vorlage ist ein ausgefüllter Filter, nichts weiter. Nimm eine, ändere eine Zeile, und sie ist deine.',
    'herald.probe': 'Probe',
    'herald.remove': 'Entfernen',
    'herald.chats': 'Kanäle finden',
    'herald.quiet': 'Es geht nichts hinaus, bevor du auf senden drückst.',
    'report.head': 'Bericht — viele Züge, eine Nachricht',
    'report.sent': 'Bericht ist raus.',
    'report.saved': 'Gesichert.',
    'build.head': 'Bau',
    'chat.head': 'Reden',
    'lane.dev': 'dev',
    'lane.prod': 'prod',
    'card.onDev': 'auf development — was dev fährt, enthält die Commits dieser Karte',
    'card.onProd': 'auf production — was main fährt, enthält die Commits dieser Karte',
    'card.notOnDev': 'noch nicht auf development',
    'card.notOnProd': 'noch nicht auf production',
    'card.deployed': 'ausgerollt',
  },
};

const KEY = 'gradula-language';

/**
 * Which language. The stored choice first, then the browser's, then German —
 * German because whoever has not chosen is standing in this house, and this
 * house speaks German out loud even where its code does not.
 */
export function chosenLanguage(): Language {
  try {
    const held = localStorage.getItem(KEY);
    if (held === 'de' || held === 'en') return held;
  } catch { /* a browser that forbids storage still gets a language */ }
  const asked = (globalThis.navigator?.language ?? '').slice(0, 2).toLowerCase();
  return asked === 'en' ? 'en' : 'de';
}

/** Remember the choice. The page is reloaded by the caller, not here. */
export function keepLanguage(language: Language): void {
  try { localStorage.setItem(KEY, language); } catch { /* then it holds for this visit */ }
}

/**
 * A word for people. A missing twin comes back as the KEY, not as an empty
 * string: a surface with a visible identifier is ugly, one without text is
 * broken, and only the ugly one gets fixed.
 *
 * The `fallback` is for words that COME FROM THE SERVICE with a sentence
 * already attached — a finding, say. The service names it in English and the
 * surface may know it better; a finding this surface has never heard of still
 * shows the service's own line rather than an identifier.
 */
export function words(language: Language) {
  const surface = SURFACE[language] ?? SURFACE.de;
  const vocabulary = WORDS[language] ?? WORDS.de;
  return (key: string, fallback?: string): string => surface[key] ?? vocabulary[key] ?? fallback ?? key;
}
